on: push
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.6
      with:
        server: ftp-bodygreg.alwaysdata.net
        username: bodygreg
        password: ${{ secrets.ftp_password }}
        secure: true
        secure-options: "unauthorized"
        server-dir: /www/
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
        
